[upgrade] stop processes before deleting namespaces
SUSE-Cloud/cookbook-openstack-network pull request #16
Opened 2017-01-13 12:58 UTC by rhafer

https://bugzilla.suse.com/show_bug.cgi?id=1018582

2017-01-13 12:59 UTC, rhafer commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) S53P1 bsc#1018582 - neutron-ha-tool --ssh-delete-namespace doesn't completely remove the namespace](https://trello.com/c/5jAtIm9y/254-3-s53p1-bsc-1018582-neutron-ha-tool-ssh-delete-namespace-doesn-t-completely-remove-the-namespace)

2017-01-13 13:23 UTC, AbelNavarro approved these changes
Interesting. Now we know why some namespaces couldn't be deleted, because of dangling processes.

2017-01-13 13:36 UTC, aplanas requested changes

2017-01-13 13:36 UTC, aplanas commented on files/default/neutron-ha-tool.py
> +        self.ssh_client.connect(self.target_host, timeout=10)
I would not add connection logic inside the constructor

2017-01-13 13:36 UTC, aplanas commented on files/default/neutron-ha-tool.py
> +        return [rc, out_lines]
Jeje is like Go.

I would use a different approach here: raise an exception if rc is an error code

2017-01-13 13:36 UTC, aplanas commented on files/default/neutron-ha-tool.py
> +        out_lines = stdout.readlines()
I see a pattern below where you `.strip()` this, maybe is better to add the strips here

2017-01-13 13:36 UTC, aplanas commented on files/default/neutron-ha-tool.py
> +        return self.namespace in [ns.strip() for ns in out_lines]
if the strips are move inside the `_simple_ssh_command` this will become `self.namespace in out_lines`

2017-01-13 13:36 UTC, aplanas commented on files/default/neutron-ha-tool.py
> +                return [0, []]
I am not sure that this is OK, I think that you want to return an empty array, like in the success case.

2017-01-16 11:18 UTC, rhafer commented on files/default/neutron-ha-tool.py
> +                return [0, []]
Hm, true (it's a leftover that I missed to cleanup :( ). Though it's not supposed to return  an empty array. ```return None``` is what I need here.

2017-01-16 11:23 UTC, rhafer commented on files/default/neutron-ha-tool.py
> +        return [rc, out_lines]
There are some case where I need to consider ```rc != 0``` as a non-error condition, that's why I didn't want to throw exceptions. (see e.g. ```_get_namespace_pids()```)

2017-01-16 11:40 UTC, aplanas commented on files/default/neutron-ha-tool.py
> +        return [rc, out_lines]
Ok for me.

2017-01-16 12:57 UTC, rhafer commented on files/default/neutron-ha-tool.py
> +        self.ssh_client.connect(self.target_host, timeout=10)
@aplanas Ok. I moved that to the ```delete_router_namespace``` method

2017-01-16 12:58 UTC, rhafer commented on files/default/neutron-ha-tool.py
> +        out_lines = stdout.readlines()
@aplanas Yeah, makes sense.

2017-01-16 13:07 UTC, aplanas approved these changes

2017-01-16 13:27 UTC, nicolasbock approved these changes

2017-01-19 10:37 UTC, merged