Fix agent re-balancing (bsc#1029297)
SUSE-Cloud/cookbook-openstack-network pull request #27
Opened 2017-03-14 10:23 UTC by matelakat

The original implementation was broken, and did not rebalance the number
of routers between agents. This new implementation provides a
deterministic way to re-balance the routers between agents.

2017-03-14 17:22 UTC, aspiers requested changes
At a glance this seems like quite a significant change.  If it's not appropriate to break it into multiple commits then please can you expand the commit message to explain what the change does, so we don't have to reverse engineer it from scratch whilst reviewing.

Also please can you comment on whether #2 is still relevant, and if so, whether this PR obsoletes it?

2017-03-21 09:59 UTC, matelakat commented
@aspiers @aplanas @rhafer Change has been reworked, hopefully for the better, could you guys review this?

2017-03-21 11:48 UTC, aspiers requested changes

2017-03-21 11:48 UTC, aspiers commented on files/default/neutron-ha-tool.py
> +    while agent_list.calculate_maximal_router_count_difference() > 1:
This `while` loop makes sense, but contradicts the commit message which seems to say that only a single router will be moved.  Can you fix the commit message?

2017-03-21 11:52 UTC, matelakat commented on files/default/neutron-ha-tool.py
> +    while agent_list.calculate_maximal_router_count_difference() > 1:
Fixed

2017-03-21 12:00 UTC, aspiers requested changes
Just one tiny nitpick, but otherwise looks beautiful to me.

2017-03-21 12:00 UTC, aspiers commented on files/default/test-neutron-ha-tool.py
> +def make_neutron_with_distribution(router_distribution):
I think `fake_neutron_with_distribution` would be a bit clearer here.

2017-03-21 12:00 UTC, aspiers commented on files/default/neutron-ha-tool.py
> +    while agent_list.calculate_maximal_router_count_difference() > 1:
Much better, thanks!  In fact, I'd now describe this commit as beautifully clear and clean code :-)

2017-03-22 09:58 UTC, matelakat commented
rebasing...

2017-03-22 14:22 UTC, matelakat commented
@aspiers @aplanas is this good to go now?

2017-04-02 23:57 UTC, aspiers approved these changes

2017-04-05 08:29 UTC, aspiers commented
@rhafer Please can you review this? I haven't checked but I'm worried it might conflict with #29, and it's earlier in the queue :)

2017-04-05 10:50 UTC, rhafer approved these changes
There is one thing that I am not 100% sure about and that is the handling of agent that have "admin_state_up" set to "False". Agents with that setting can still be hosting active routers. If I understand it correctly those agents will be completely ignored by the new rebalancing code, right? (Which is the right thing to do I think, it just means you will not end up with a completely balanced setup after running the script, it might worth mentioning that in the commit message or a comment)

Other than that I think this is really nice and clean work. Thanks a lot!

2017-04-05 11:46 UTC, rhafer commented
> Please can you review this?

Done

> I haven't checked but I'm worried it might conflict with #29, and it's earlier in the queue :)

AFAICS it's doesn't conflict.

2017-04-05 11:51 UTC, aspiers commented
> AFAICS it's doesn't conflict.

I checked and it doesn't.

2017-04-05 11:51 UTC, merged