Check L3 agent mode before migration
SUSE-Cloud/cookbook-openstack-network pull request #34
Opened 2017-07-07 16:38 UTC by stefannica

The --l3-agent-migrate option now also checks the mode
(dvr/dvr_snat/legacy) of the target candidate L3 agents,
which corrects the L3 agent mismatch errors seen in DVR
setups, such as migrating a distributed router from a
dvr_snat L3 agent to a dvr only L3 agent.

2017-07-07 16:41 UTC, stefannica commented
![](https://github.trello.services/images/mini-trello-icon.png) [P2: Bug 1046857 - #L3 In HA setup not all ports / namespaces come up after the reboot of a node](https://trello.com/c/84t68MQO/340-p2-bug-1046857-l3-in-ha-setup-not-all-ports-namespaces-come-up-after-the-reboot-of-a-node)

2017-07-07 16:53 UTC, stefannica commented
Forgot to add some tests for these DVR scenarios

2017-07-11 08:05 UTC, stefannica commented
I tested this on an HA/DVR setup by having a VM pinging the internet and using three approaches to trigger the neutron-ha-tool:
- manually invoking 'neutron-ha-tool --l3-agent-evacuate'
- putting one controller node in maintenance mode and stopping the l3 agent on it
- powering off one controller node

In all cases, the routers have been migrated to another controller and after a brief pause, the outside VM traffic was successfully resumed.

2017-07-11 08:12 UTC, jsuchome commented
Could you test it in the Cloud6-7 upgrade scenario?

2017-07-11 11:12 UTC, stefannica commented
I updated the fix to completely ignore offline dvr-only L3 agents. The previous version only removed the routers from offline dvr-only L3 agents, but had another undesired effect: when powering off the main controller node, sometimes the neutron-ha-tool finds all L3 agents offline except one (probably the one running on the other controller node), which leads to the removal of routers from all dvr-only L3 agents, which practically disrupts all external access for all VMs.
The new approach is to leave offline dvr-only L3 agents untouched. The fact that they still show up in the list of L3 agents hosting a router is harmless (doesn't eat up any resources) and the operation of migrating routers to another dvr-only L3 agent is a nonsense.

2017-07-11 12:17 UTC, AbelNavarro approved these changes

2017-07-12 08:43 UTC, stefannica commented
@jsuchome, the Cloud7 Upgrade HA/DVR job passed. There was just one tempest test that failed during the job execution, but then subsequently passed when I re-executed tempest manually - probably a parallel execution timing fluke.

2017-07-12 09:11 UTC, jsuchome commented
@stefannica Nice, thanks a lot!

Now, I won't block this review, but I also do not feel confident regarding this code to approve it ... hopefully @aplanas or @matelakat can do the review...

2017-07-12 10:07 UTC, matelakat requested changes
I think this PR contains several Fixes, not just one. We would need to separate those changes to separate commits, otherwise it's hard to understand. For example, there is a refactoring step, which I think is not needed. There is also adding an extra filter on `admin_state_up` which might need a bit of explanation. Also, I think neutron-ha-tool does not want to deal with dvr routers, so why don't we filter out them on the lowest level? see that all the callers of `list_dead_agents` have their `exclude_agent_mode` set to dvr. Also the tests would need some refactoring - I included some suggestions on that as well, but I can live with them as they are, but I expect each change to have a separate change, which we don't have at the moment (see admin_state_up modification)

2017-07-12 10:07 UTC, matelakat commented on files/default/test-neutron-ha-tool.py
> +        self.assertEqual(1, error_count)
Why did it change?

2017-07-12 10:07 UTC, matelakat commented on files/default/test-neutron-ha-tool.py
> +def setup_fake_neutron(live_agents=0, dead_agents=0,
I would amend this method instead of adding a new one. The setup code is not really pleasant to read. It would be better if we could say:
```python
setup_fake_neutron(2*[DeadAgent()], 3*[LiveAgent()], 1*[LiveAgent(mode='dvr')])
```
Instead of using update_fake_neutron. Mutating too much these fakes is not a good idea either. Also `update` is a quite generic word to use.

2017-07-12 10:07 UTC, matelakat commented on files/default/test-neutron-ha-tool.py
> +        update_fake_neutron(fake_neutron, live_agents=2, agent_mode='dvr')
You can see that this above doesn't read nicely. You have to look at the code for `update_fake_neutron` to understand what is the starting state. See my previous comment.

2017-07-12 10:07 UTC, matelakat commented on files/default/neutron-ha-tool.py
> +            agent['admin_state_up'] is True and
This `admin_state_up` is a separate fix, isn't it?

2017-07-12 10:07 UTC, matelakat commented on files/default/neutron-ha-tool.py
> +        agent_dead_list_old = agent_dead_list
why is this change? Is it a refactoring step?

2017-07-12 12:25 UTC, stefannica commented on files/default/test-neutron-ha-tool.py
> +def setup_fake_neutron(live_agents=0, dead_agents=0,
Agreed. I refactored the tests to do something similar to your suggestion.

2017-07-12 12:25 UTC, stefannica commented on files/default/test-neutron-ha-tool.py
> +        update_fake_neutron(fake_neutron, live_agents=2, agent_mode='dvr')
That's right, it looks much nicer with the new mode.

2017-07-12 12:29 UTC, stefannica commented on files/default/test-neutron-ha-tool.py
> +        self.assertEqual(1, error_count)
My mistake. I reverted it to the previous behaviour.

2017-07-12 12:31 UTC, stefannica commented on files/default/neutron-ha-tool.py
> +        agent_dead_list_old = agent_dead_list
Yes, it was a refactoring change. It wasn't necessary and I removed it.

2017-07-12 12:37 UTC, stefannica commented on files/default/neutron-ha-tool.py
> +            agent['admin_state_up'] is True and
Yes, it is a separate fix, but with the latest update completely replacing the target_agent_list with the list_alive_l3_agents, this fix is completely factored into the changeset, so it's impossible to detach from it.

2017-07-12 12:40 UTC, stefannica commented
@matelakat, I removed the refactoring bit, filtered dvr l3 agents globally and updated the unittests as you suggested. However, as a result, the 'admin_state_up' fix is no longer obvious and cannot be detached in a separate commit. What do you suggest I do ?

2017-07-13 08:13 UTC, stefannica commented
@matelakat, please disregard my previous question. I found a way to separate the changes.

2017-07-13 08:17 UTC, matelakat requested changes
@stefannica This change is still a mix of a refactorings and fixes:
 - refactor: use list_alive_l3_agents
 - refactor: list_dead_l3_agents
 - fix: fix comments of migrate_router
 - fix: exclude dvr routers
 
I would prefer if we didn't put the responsibility of filtering out an agent to the list_alive_agents, let's leave a separate function for that. It reads very badly: "Give me all the agents, expect this one"

Also in the tests the setup_fake_agent is not quite descriptive, so it's hard to tell that this line will set up 2 live agents:
```python
fake_neutron = setup_fake_neutron(2*[setup_fake_agent()])
```

2017-07-13 08:18 UTC, matelakat commented
@stefannica Please add a test for the admin_state_up change as well to the same commit

2017-07-13 09:57 UTC, stefannica commented
@matelakat, that's the best I can do wrt separating changes in individual commits. A bit overkill IMO, but here it is nevertheless.

2017-07-13 10:12 UTC, matelakat approved these changes
@stefannica Thank you for your effort, it was much easier to review the change.

2017-07-13 10:13 UTC, merged